import {useEffect,useState} from 'react';
import {ArrowLeft,CheckCircle2,KeyRound,LockKeyhole,ShieldCheck} from 'lucide-react';
import {getSupabase,resetCurrentPassword} from './auth';

export default function ResetPasswordPage(){
 const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[ready,setReady]=useState(false);
 useEffect(()=>{let alive=true;getSupabase().auth.getSession().then(()=>{if(alive)setReady(true)}).catch(e=>{if(alive){setError(e instanceof Error?e.message:'เปิดลิงก์รีเซ็ตไม่สำเร็จ');setReady(true)}});return()=>{alive=false}},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{setNotice(await resetCurrentPassword(password,confirm));setPassword('');setConfirm('');window.history.replaceState(null,'','/auth/reset/')}catch(err){setError(err instanceof Error?err.message:'ตั้งรหัสผ่านใหม่ไม่สำเร็จ')}finally{setBusy(false)}}
 return <main className="auth-page reset-page"><section className="auth-card auth-card-wide reset-card"><div className="auth-panel-copy"><a className="reset-back" href="/trial/drugs/?auth=login"><ArrowLeft size={17}/>กลับหน้าเข้าสู่ระบบ</a><div className="auth-icon"><LockKeyhole size={30}/></div><span>CAT-ALYSIM PASSWORD RECOVERY</span><h1>ตั้งรหัสผ่านใหม่สำหรับบัญชีของคุณ</h1><p>หน้านี้ใช้ลิงก์จากอีเมลรีเซ็ตรหัสผ่านแบบเดียวกับ Desktop App หลังตั้งรหัสใหม่สำเร็จ ระบบจะออกจาก session ชั่วคราวเพื่อให้เข้าสู่ระบบใหม่อย่างสะอาด</p><div className="auth-steps"><div><CheckCircle2 size={16}/> Supabase Recovery</div><div><CheckCircle2 size={16}/> Strong Password</div><div><CheckCircle2 size={16}/> Secure Sign-out</div></div></div><div className="auth-form-pane">
  <form className="auth-stack" onSubmit={submit}><div className="reset-form-heading"><ShieldCheck size={18}/><h2>Reset Password</h2></div><p>กรอกรหัสผ่านใหม่อย่างน้อย 10 ตัวอักษร มีตัวพิมพ์เล็ก พิมพ์ใหญ่ ตัวเลข และสัญลักษณ์</p><label><span>รหัสผ่านใหม่</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password" autoFocus/></label><label><span>ยืนยันรหัสผ่านใหม่</span><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/></label>{notice&&<div className="auth-notice">{notice}</div>}{error&&<div className="auth-error multi-line">{error}</div>}<button disabled={busy||!ready}><KeyRound size={18}/>{busy?'กำลังบันทึก...':'บันทึกรหัสผ่านใหม่'}</button><a className="reset-login-link" href="/trial/drugs/?auth=login">เข้าสู่ระบบด้วยรหัสผ่านใหม่</a></form>
 </div></section></main>;
}
