import {useEffect,useMemo,useState} from 'react';
import {UploadCloud,FileText,ShieldCheck,Package,UserRound,Landmark,Save,Download,Plus,Trash2,CheckCircle2,AlertCircle,NotebookPen,ArrowLeft,CalendarDays,CreditCard,KeyRound} from 'lucide-react';
import type {CaseData,Person,PropertyItem,ImprisonItem,Profile,MemoRow} from './types';
import {upload,saveCase,getDocuments,generate,generateOne} from './api';
import {getAuthContext,loadTrialProfile,saveTrialProfile,verifyPaidSerial} from './auth';

const blankPerson=():Person=>({prefix:'',name:'',lastname:'',age:'',id_card:'',nationality:'ไทย',occupation:'',address:'',phone:'',statement:'',arrest_case:false,duty:'',position:'',station:''});
const blankProperty=(n=1):PropertyItem=>({item_no:String(n),item_name:'',quantity:'1',unit:'รายการ',all_drugs:'',pure_drugs:'',price:''});
const blankImprison=(n=1):ImprisonItem=>({imprison_no:String(n),imprison_request:'',request_date:'',start_date:'',end_date:''});
const blankMemo=():MemoRow=>({date:'',action:'',sign:''});
const blankProfile:Profile={rank:'',name:'',lastname:'',position:'พนักงานสอบสวน',station:'',phone:'',ordinal_number:'',superintendent_rank:'พ.ต.อ.',superintendent_name:''};
const initial:CaseData={caseid:'',charge:'',law:'',circumstances:'',occur:'',location:'',report1_no:'',report1_date:'',summary_date:'',court:'',evidence_number:'',evidence_date:'',imprison_number:'',accusers:[blankPerson()],suspects:[blankPerson()],witnesses:[],properties:[blankProperty()],imprisonments:[],memo_rows:[],profile:blankProfile,raw_text:'',extra:{}};
const tabs=[['import','นำเข้า','ลากบันทึกจับกุม',UploadCloud],['info','Info','ข้อมูลคดีและบุคคล',FileText],['imprison','Imprison','ฝากขังและควบคุม',Landmark],['property','Property','ของกลางยาเสพติด',Package],['profile','Profile','ข้อมูลผู้ใช้งาน',UserRound],['memo','Memo','บันทึกพนักงานสอบสวน',NotebookPen],['generate','Generate','สร้างเอกสาร',Download]] as const;



type Tab=typeof tabs[number][0];
function Field({label,value,onChange,wide=false,full=false,type='text',placeholder=''}:{label:string,value:string,onChange:(v:string)=>void,wide?:boolean,full?:boolean,type?:string,placeholder?:string}){const cls=full?'field full':wide?'field wide':'field';return <label className={cls}><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function TextArea({label,value,onChange,rows=5,action}:{label:string,value:string,onChange:(v:string)=>void,rows?:number,action?:React.ReactNode}){return <label className="field full textarea-field"><span className="field-label-row"><span>{label}</span>{action}</span><textarea rows={rows} value={value} onChange={e=>onChange(e.target.value)}/></label>}
const DUTY_OPTIONS:[string,string][]=[['','เลือกหน้าที่'],['head','หัวหน้าชุดจับกุม'],['deputy','รองหัวหน้าชุดจับกุม'],['arrest_team','เจ้าหน้าที่ชุดจับกุม'],['search','ผู้ตรวจค้น'],['custody','ผู้ควบคุมตัวผู้ต้องหา'],['seize','ผู้ตรวจยึดของกลาง'],['record','ผู้บันทึกการจับกุม'],['photo','ผู้บันทึกภาพ'],['witness','พยานในการจับกุม']];
function SelectField({label,value,onChange,options,wide=false}:{label:string,value:string,onChange:(v:string)=>void,options:[string,string][],wide?:boolean}){return <label className={wide?'field wide':'field'}><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>}
const TH_MONTHS=['','มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม'];
function thaiDate(value:string){if(!value)return '—';const m=value.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)return value;return `${Number(m[3])} ${TH_MONTHS[Number(m[2])]} ${Number(m[1])+543}`}
function ThaiDateField({label,value,onChange}:{label:string,value:string,onChange:(v:string)=>void}){return <label className="field thai-date-field"><span>{label}</span><input type="date" value={value} onChange={e=>onChange(e.target.value)}/><strong>{thaiDate(value)}</strong></label>}
function SectionTitle({eyebrow,title,desc}:{eyebrow:string,title:string,desc:string}){return <div className="section-title"><span>{eyebrow}</span><h2>{title}</h2><p>{desc}</p></div>}

function PersonEditor({title,items,setItems,accent,circumstances,showArrestFields=false}:{title:string,items:Person[],setItems:(v:Person[])=>void,accent:string,circumstances:string,showArrestFields?:boolean}){
 const update=(i:number,k:keyof Person,v:string|boolean)=>setItems(items.map((x,n)=>n===i?{...x,[k]:v}:x));
 return <section className="editor-card person-editor-card" style={{'--accent':accent} as React.CSSProperties}>
  <div className="card-head"><div><small>บุคคล</small><h3>{title}</h3></div><button className="ghost" onClick={()=>setItems([...items,blankPerson()])}><Plus size={17}/> เพิ่ม</button></div>
  {items.length===0?<button className="empty-add" onClick={()=>setItems([blankPerson()])}>+ เพิ่มข้อมูล{title}</button>:items.map((p,i)=><div className="person-block" key={i}>
   <div className="person-no">{i+1}</div>
   <div className="form-grid person-form-grid">
    <Field label="คำนำหน้า" value={p.prefix} onChange={v=>update(i,'prefix',v)}/><Field label="ชื่อ" value={p.name} onChange={v=>update(i,'name',v)}/><Field label="นามสกุล" value={p.lastname} onChange={v=>update(i,'lastname',v)}/><Field label="อายุ" value={p.age} onChange={v=>update(i,'age',v)}/>
    <Field label="เลขบัตรประชาชน" value={p.id_card} onChange={v=>update(i,'id_card',v)} wide/><Field label="สัญชาติ" value={p.nationality} onChange={v=>update(i,'nationality',v)}/><Field label="อาชีพ" value={p.occupation} onChange={v=>update(i,'occupation',v)}/><Field label="โทรศัพท์" value={p.phone} onChange={v=>update(i,'phone',v)}/><Field label="ที่อยู่" value={p.address} onChange={v=>update(i,'address',v)} wide/>
    {showArrestFields&&<><label className="field arrest-toggle"><span>กรณีจับกุม</span><button type="button" className={p.arrest_case?'toggle-button on':'toggle-button'} onClick={()=>update(i,'arrest_case',!p.arrest_case)}><i/>{p.arrest_case?'เป็นชุดจับกุม':'ไม่ใช่ชุดจับกุม'}</button></label><Field label="ตำแหน่ง" value={p.position} onChange={v=>update(i,'position',v)} placeholder="เช่น รอง สว.(สส.)"/><Field label="สังกัด" value={p.station} onChange={v=>update(i,'station',v)} placeholder="เช่น สน.พหลโยธิน"/><SelectField label="หน้าที่ในชุดจับกุม" value={p.duty} onChange={v=>update(i,'duty',v)} options={DUTY_OPTIONS}/></>}
    <TextArea label="คำให้การ/หมายเหตุ" value={p.statement} onChange={v=>update(i,'statement',v)} rows={5} action={<button type="button" className="inline-copy" onClick={()=>update(i,'statement',circumstances)}>ดึงจากพฤติการณ์</button>}/>
   </div>
   <button className="icon-danger" onClick={()=>setItems(items.filter((_,n)=>n!==i))}><Trash2 size={17}/></button>
  </div>)}
 </section>
}
function addDaysISO(value:string,days:number){if(!value)return '';const d=new Date(`${value}T12:00:00`);if(Number.isNaN(d.getTime()))return '';d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function profileSign(profile:Profile){return [profile.rank,profile.name,profile.lastname].filter(Boolean).join(' ').trim()}
function buildImprisonRounds(firstDate:string):ImprisonItem[]{if(!firstDate)return [];return Array.from({length:7},(_,i)=>{const start=addDaysISO(firstDate,i*12);const end=addDaysISO(firstDate,(i+1)*12-1);return {imprison_no:String(i+1),imprison_request:i===0?'คำร้องขอฝากขังครั้งที่ 1':`คำร้องขอฝากขังครั้งที่ ${i+1}`,request_date:start,start_date:start,end_date:end}})}
function detectMemoRows(data:CaseData):MemoRow[]{const sign=profileSign(data.profile);const rows:MemoRow[]=[];const push=(date:string,action:string)=>{if(action.trim())rows.push({date,action,sign})};push(data.report1_date,`รับแจ้งและลงรายงานประจำวัน${data.report1_no?` เลขที่ ${data.report1_no}`:''}`);if(data.occur||data.circumstances)push(data.report1_date||data.evidence_date,`ตรวจสอบข้อเท็จจริงและพฤติการณ์แห่งคดี${data.occur?` เหตุเกิด ${data.occur}`:''}${data.location?` ณ ${data.location}`:''}`);data.accusers.forEach(p=>push(data.report1_date,`สอบปากคำผู้กล่าวหา ${[p.prefix,p.name,p.lastname].filter(Boolean).join(' ')}${p.duty?` หน้าที่ ${p.duty}`:''}`));data.suspects.forEach(p=>push(data.report1_date,`แจ้งข้อกล่าวหาและสอบปากคำผู้ต้องหา ${[p.prefix,p.name,p.lastname].filter(Boolean).join(' ')}`));data.witnesses.forEach(p=>push(data.report1_date,`สอบปากคำพยาน ${[p.prefix,p.name,p.lastname].filter(Boolean).join(' ')}${p.duty?` หน้าที่ ${p.duty}`:''}`));if(data.properties.some(x=>x.item_name))push(data.evidence_date,`ตรวจยึดและจัดทำบัญชีของกลาง จำนวน ${data.properties.filter(x=>x.item_name).length} รายการ`);data.imprisonments.forEach(x=>push(x.request_date,`ยื่นคำร้องฝากขังครั้งที่ ${x.imprison_no} กำหนดถึงวันที่ ${x.end_date||'-'}`));push(data.summary_date,'สรุปสำนวนการสอบสวนและจัดทำความเห็นทางคดี');return rows}
function documentCategory(id:string){const first=id.split('/')[0];if(id.includes('/'))return first;if(/คำให้การ/.test(id))return 'คำให้การ';if(/ของกลาง|ตรวจพิสูจน์|ฉลาก/.test(id))return 'ของกลางและตรวจพิสูจน์';if(/ฝากขัง|ควบคุม/.test(id))return 'ฝากขังและควบคุมตัว';if(/รายงานการสอบสวน|หนังสือส่งสำนวน|บัญชีท้าย/.test(id))return 'รายงานและส่งสำนวน';if(/บันทึก/.test(id))return 'บันทึก';return 'เอกสารหลัก'}
const categoryOrder=['เอกสารหลัก','บันทึก','คำให้การ','ของกลางและตรวจพิสูจน์','ฝากขังและควบคุมตัว','รายงานและส่งสำนวน','ผัดฟ้องฝากขังศาลแขวง','ฝากขังศาลอาญา','หมายจับ','หมายเรียกผู้ต้องหา'];
export default function TrialApp(){
 const [active,setActive]=useState<Tab>('import');const [data,setData]=useState<CaseData>(initial);const [docs,setDocs]=useState<{id:string,name:string}[]>([]);const [selected,setSelected]=useState<string[]>([]);const [multiSelect,setMultiSelect]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [drag,setDrag]=useState(false);
 const [paidSerial,setPaidSerial]=useState('');const [authContext,setAuthContext]=useState(()=>getAuthContext());
 const memoSignature=profileSign(data.profile);
 const accountProfile=(authContext?.profile||authContext?.license?.profile||{}) as Record<string,unknown>;
 const licenseType=String(authContext?.license?.license_type||accountProfile.status||'trial');
 const isLifetime=licenseType==='paid'||licenseType==='admin'||accountProfile.status==='active'||Boolean(accountProfile.paid_at);
 const savedSerial=typeof accountProfile.serial_key==='string'?accountProfile.serial_key:'';
 const licenseTitle=isLifetime?'ตลอดชีพ':'Trial';
 const licenseText=isLifetime?'เปิด Full License แล้ว ใช้งานเว็บและแอพได้ต่อเนื่อง':'บัญชีนี้อยู่ในช่วงทดลองใช้งาน อัปเกรดเป็นตลอดชีพได้ทุกเวลา';
 const groupedDocs=useMemo(()=>{const groups=new Map<string,{id:string,name:string}[]>();docs.forEach(d=>{const c=documentCategory(d.id);groups.set(c,[...(groups.get(c)||[]),d])});groups.forEach((items,key)=>groups.set(key,[...items].sort((a,b)=>a.name.localeCompare(b.name,'th',{numeric:true})))) ;return [...groups.entries()].sort((a,b)=>{const ai=categoryOrder.indexOf(a[0]),bi=categoryOrder.indexOf(b[0]);return (ai<0?999:ai)-(bi<0?999:bi)||a[0].localeCompare(b[0],'th')})},[docs]);
 useEffect(()=>{getDocuments().then(x=>{setDocs(x);setSelected([])}).catch(()=>{})},[]);
 useEffect(()=>{loadTrialProfile(blankProfile).then(profile=>setData(d=>({...d,profile}))).catch(()=>{})},[]);
 const progress=useMemo(()=>{let n=0;if(data.caseid)n++;if(data.charge)n++;if(data.suspects.some(x=>x.name))n++;if(data.properties.some(x=>x.item_name))n++;if(data.profile.name&&data.profile.station)n++;return Math.round(n/5*100)},[data]);
 const set=<K extends keyof CaseData>(k:K,v:CaseData[K])=>setData(d=>({...d,[k]:v}));
 async function importFile(file?:File){if(!file)return;setBusy(true);setMessage('กำลังอ่านบันทึกจับกุม...');try{const parsed=await upload(file);setData(d=>({...d,...parsed,profile:d.profile,extra:{...d.extra,warnings:parsed.warnings,confidence:parsed.confidence}}));setMessage('อ่านข้อมูลสำเร็จ ตรวจทานในแท็บ Info ต่อได้เลย');setActive('info')}catch(e){setMessage(e instanceof Error?e.message:'อ่านไฟล์ไม่สำเร็จ')}finally{setBusy(false)}}
 function normalizedCase(){const sign=profileSign(data.profile);return {...data,memo_rows:data.memo_rows.map(r=>({...r,sign}))}}
 async function save(){setBusy(true);try{const saved=await saveCase(normalizedCase());setData(saved);setMessage('บันทึกคดีลงฐานข้อมูลแล้ว')}catch(e){setMessage(e instanceof Error?e.message:'บันทึกไม่สำเร็จ')}finally{setBusy(false)}}
 async function saveProfileOnly(){setBusy(true);try{await saveTrialProfile(data.profile);setMessage('บันทึกโปรไฟล์ของผู้ใช้นี้แล้ว')}catch(e){setMessage(e instanceof Error?e.message:'บันทึกโปรไฟล์ไม่สำเร็จ')}finally{setBusy(false)}}
 async function activatePaidSerial(){if(!paidSerial.trim()){setMessage('กรอก Serial ตลอดชีพก่อนยืนยัน');return}setBusy(true);try{const ctx=await verifyPaidSerial(paidSerial);setAuthContext(ctx);setPaidSerial('');setMessage('เปิดสิทธิ์ตลอดชีพให้บัญชีนี้แล้ว')}catch(e){setMessage(e instanceof Error?e.message:'ยืนยัน Serial ตลอดชีพไม่สำเร็จ')}finally{setBusy(false)}}
 async function makeDocs(){setBusy(true);setMessage('กำลังสร้างเอกสารจากแม่แบบจริง...');try{await generate(normalizedCase(),selected);setMessage('สร้างเอกสารและดาวน์โหลด ZIP แล้ว')}catch(e){setMessage(e instanceof Error?e.message:'สร้างเอกสารไม่สำเร็จ')}finally{setBusy(false)}}
 async function makeSingle(id:string,round=''){setBusy(true);setMessage('กำลังสร้างเอกสาร...');try{await generateOne(normalizedCase(),id,round);setMessage('สร้างเอกสารเรียบร้อยแล้ว')}catch(e){setMessage(e instanceof Error?e.message:'สร้างเอกสารไม่สำเร็จ')}finally{setBusy(false)}}
 function clickDocument(id:string){if(multiSelect){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}else{void makeSingle(id)}}
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">CA</div><div><strong>CAT-ALYSIM</strong><span>DRUGS WEB STUDIO</span></div></div><a className="back-home" href="/"><ArrowLeft size={17}/><span><b>กลับหน้าหลัก</b><small>เว็บไซต์ CAT-ALYSIM</small></span></a><div className="case-chip"><span>ความพร้อมของข้อมูล</span><strong>{progress}%</strong><div><i style={{width:`${progress}%`}}/></div></div><nav>{tabs.map(([id,label,desc,Icon])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}><Icon size={20}/><span><b>{label}</b><small>{desc}</small></span></button>)}</nav><div className="side-footer"><ShieldCheck size={18}/><div><b>Dynamic Full Stack</b><small>FastAPI + SQLite + DOCX</small></div></div></aside><main className="workspace"><header className="topbar"><div><span className="live-dot"/> ระบบทำงานแบบเซิร์ฟเวอร์จริง</div><div className="top-actions"><button className="secondary" onClick={save} disabled={busy}><Save size={17}/> บันทึก</button><button className="primary" onClick={()=>setActive('generate')}><Download size={17}/> สร้างเอกสาร</button></div></header>{message&&<div className="toast"><CheckCircle2 size={18}/><span>{message}</span><button onClick={()=>setMessage('')}>×</button></div>}<div className="content">{active==='import'&&<><SectionTitle eyebrow="STEP 01" title="ลากบันทึกจับกุมเข้ามา แล้วให้ระบบจัดข้อมูลให้" desc="รองรับไฟล์ DOCX และ TXT ระบบจะอ่านผู้กล่าวหา ผู้ต้องหา พยาน ของกลาง พฤติการณ์ วันเวลา และข้อมูลคดี แล้วส่งต่อไปยังแท็บที่เกี่ยวข้อง"/><div className={drag?'dropzone drag':'dropzone'} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);importFile(e.dataTransfer.files[0])}}><div className="drop-visual"><UploadCloud size={42}/></div><h3>{busy?'กำลังวิเคราะห์เอกสาร...':'วางไฟล์บันทึกจับกุมตรงนี้'}</h3><p>หรือลองเลือกไฟล์จากเครื่อง ระบบจะไม่สร้างเอกสารจนกว่าคุณตรวจทานและกดสั่งเอง</p><label className="file-button"><input type="file" accept=".docx,.txt,.md" onChange={e=>importFile(e.target.files?.[0])}/>เลือกไฟล์บันทึกจับกุม</label></div>{data.raw_text&&<div className="raw-preview"><div><FileText size={19}/><b>ข้อความที่อ่านได้</b></div><pre>{data.raw_text.slice(0,5000)}</pre></div>}</>}
 {active==='info'&&<><SectionTitle eyebrow="INFO" title="ข้อมูลคดีและบุคคล" desc="รวมข้อมูลหลักของคดียาเสพติดไว้ในหน้าเดียว แต่แยกกลุ่มสีเพื่อให้ตรวจทานได้เร็วและไม่ลายตา"/><section className="editor-card info-card"><div className="card-head"><div><small>ข้อมูลคดี</small><h3>รายละเอียดหลัก</h3></div></div><div className="form-grid"><Field label="เลขคดี" value={data.caseid} onChange={v=>set('caseid',v)}/><Field label="เลขรายงานประจำวัน" value={data.report1_no} onChange={v=>set('report1_no',v)}/><Field label="วันที่รายงานประจำวัน" type="date" value={data.report1_date} onChange={v=>set('report1_date',v)}/><Field label="วันที่สรุปสำนวนการสอบสวน" type="date" value={data.summary_date} onChange={v=>set('summary_date',v)}/><Field label="วันที่/เวลาเกิดเหตุ" value={data.occur} onChange={v=>set('occur',v)}/><Field label="สถานที่เกิดเหตุ" value={data.location} onChange={v=>set('location',v)} wide/><Field label="ศาล" value={data.court} onChange={v=>set('court',v)}/><Field label="ข้อหา" value={data.charge} onChange={v=>set('charge',v)} full/><Field label="บทกฎหมาย" value={data.law} onChange={v=>set('law',v)} full/><TextArea label="พฤติการณ์" value={data.circumstances} onChange={v=>set('circumstances',v)} rows={8}/></div></section><PersonEditor title="ผู้กล่าวหา" items={data.accusers} setItems={v=>set('accusers',v)} accent="#315efb" circumstances={data.circumstances} showArrestFields/><PersonEditor title="ผู้ต้องหา" items={data.suspects} setItems={v=>set('suspects',v)} accent="#ef6c4d" circumstances={data.circumstances}/><PersonEditor title="พยาน" items={data.witnesses} setItems={v=>set('witnesses',v)} accent="#27a878" circumstances={data.circumstances} showArrestFields/></>}
 {active==='imprison'&&<><SectionTitle eyebrow="IMPRISON" title="ควบคุมตัวและฝากขัง" desc="กำหนดวันยื่นครั้งแรกเพียงครั้งเดียว ระบบคำนวณรอบที่ 1–7 ให้อัตโนมัติ พร้อมสร้างเอกสารจากแต่ละรอบได้ตรงหน้า"/><section className="imprison-setup"><div className="imprison-setup-icon"><CalendarDays size={25}/></div><div className="imprison-setup-copy"><small>ตั้งค่ารอบฝากขัง</small><h3>วันยื่นคำร้องครั้งที่ 1</h3><p>เลือกรอบแรกแล้วระบบจะคำนวณวันเริ่มและสิ้นสุดต่อเนื่องรอบละ 12 วัน</p></div><ThaiDateField label="เลือกวันที่ยื่นครั้งแรก" value={data.imprisonments[0]?.request_date||''} onChange={v=>{const rounds=buildImprisonRounds(v);set('imprisonments',rounds);set('imprison_number',rounds.length?'7':'')}}/></section><div className="imprison-stage">{data.imprisonments.length===0?<div className="blank-state imprison-empty"><Landmark size={40}/><h3>ยังไม่มีรอบฝากขัง</h3><p>เลือกวันที่ยื่นคำร้องครั้งแรกด้านบน ระบบจะสร้างรอบที่ 1–7 ให้ทันที</p></div>:<div className="imprison-timeline">{data.imprisonments.map((x,i)=><section className={i===0?'imprison-round-card featured':'imprison-round-card'} key={i}><div className="round-head"><div className="round-number"><span>รอบที่</span><strong>{x.imprison_no}</strong></div><div className="round-title"><small>{i===0?'เอกสารรอบแรก':'คำร้องรอบถัดไป'}</small><h3>{x.imprison_request||`คำร้องขอฝากขังครั้งที่ ${x.imprison_no}`}</h3></div><div className="round-status"><CheckCircle2 size={16}/>พร้อมสร้าง</div></div><div className="round-date-strip"><ThaiDateField label="วันที่ยื่นคำร้อง" value={x.request_date} onChange={v=>set('imprisonments',data.imprisonments.map((q,n)=>n===i?{...q,request_date:v}:q))}/><ThaiDateField label="เริ่มควบคุม" value={x.start_date} onChange={v=>set('imprisonments',data.imprisonments.map((q,n)=>n===i?{...q,start_date:v}:q))}/><ThaiDateField label="สิ้นสุด" value={x.end_date} onChange={v=>set('imprisonments',data.imprisonments.map((q,n)=>n===i?{...q,end_date:v}:q))}/></div><div className="round-bottom"><Field label="รายละเอียดคำร้อง" value={x.imprison_request} onChange={v=>set('imprisonments',data.imprisonments.map((q,n)=>n===i?{...q,imprison_request:v}:q))} full/><div className="round-actions">{i===0?<><button className="primary small" disabled={busy} onClick={()=>makeSingle('ฝากขังศาลอาญา/คำร้องขอฝากขังครั้งที่ 1','1')}>สร้างคำร้องครั้งที่ 1</button><button className="ghost" disabled={busy} onClick={()=>makeSingle('ฝากขังศาลอาญา/คำให้การพยาน(ฝากขัง)','1')}>คำให้การพยาน</button><button className="ghost" disabled={busy} onClick={()=>makeSingle('ฝากขังศาลอาญา/แบบยืนยันข้อเท็จจริง','1')}>แบบยืนยันข้อเท็จจริง</button></>:<button className="primary small" disabled={busy} onClick={()=>makeSingle('ฝากขังศาลอาญา/ฝากขังครั้งที่ 2-7',x.imprison_no)}>สร้างคำร้องครั้งที่ {x.imprison_no}</button>}</div></div></section>)}</div>}</div></>}
 {active==='property'&&<><SectionTitle eyebrow="PROPERTY" title="ของกลางยาเสพติด" desc="แสดงรายการแบบเต็มความกว้าง แถวละหนึ่งรายการ พร้อมใช้วันที่ยึดกลางร่วมกันทั้งคดี"/><div className="toolbar-row property-meta-row"><Field label="เลขบัญชีของกลาง" value={data.evidence_number} onChange={v=>set('evidence_number',v)}/><ThaiDateField label="วันที่ยึดของกลาง (ใช้ร่วมกันทุกรายการ)" value={data.evidence_date} onChange={v=>set('evidence_date',v)}/><button className="primary small" onClick={()=>set('properties',[...data.properties,blankProperty(data.properties.length+1)])}><Plus size={16}/>เพิ่มของกลาง</button></div><div className="property-grid property-list">{data.properties.map((x,i)=><section className="property-card property-row-card" key={i}><div className="property-top"><span>{String(i+1).padStart(2,'0')}</span><button onClick={()=>set('properties',data.properties.filter((_,n)=>n!==i))}><Trash2 size={16}/></button></div><div className="form-grid property-row-grid"><Field label="รายการของกลาง" value={x.item_name} onChange={v=>set('properties',data.properties.map((q,n)=>n===i?{...q,item_name:v}:q))}/><Field label="จำนวน" value={x.quantity} onChange={v=>set('properties',data.properties.map((q,n)=>n===i?{...q,quantity:v}:q))}/><Field label="หน่วย" value={x.unit} onChange={v=>set('properties',data.properties.map((q,n)=>n===i?{...q,unit:v}:q))}/><Field label="น้ำหนักรวม/ปริมาณยา" value={x.all_drugs} onChange={v=>set('properties',data.properties.map((q,n)=>n===i?{...q,all_drugs:v}:q))}/><Field label="สารบริสุทธิ์" value={x.pure_drugs} onChange={v=>set('properties',data.properties.map((q,n)=>n===i?{...q,pure_drugs:v}:q))}/><Field label="ราคา" value={x.price} onChange={v=>set('properties',data.properties.map((q,n)=>n===i?{...q,price:v}:q))}/></div></section>)}</div></>}
 {active==='profile'&&<><SectionTitle eyebrow="USER PROFILE" title="ข้อมูลพนักงานสอบสวน" desc="บันทึกครั้งเดียวแล้วใช้กับเอกสารทุกฉบับ ทั้งชื่อ ยศ ตำแหน่ง สถานี หมายเลขโทรศัพท์ และผู้บังคับบัญชา"/><section className={isLifetime?'license-profile-card lifetime':'license-profile-card'}><div><span><ShieldCheck size={16}/>สถานะบัญชี</span><h3>{licenseTitle}</h3><p>{licenseText}</p>{savedSerial&&<small>Serial: {savedSerial}</small>}</div><div className="license-profile-actions"><a className="secondary" href="/payment/"><CreditCard size={17}/>{isLifetime?'ดูหน้าชำระเงิน':'อัปเกรดตลอดชีพ 5,000 บาท'}</a><label><span>ใส่ Serial ตลอดชีพ</span><input value={paidSerial} onChange={e=>setPaidSerial(e.target.value)} placeholder="เช่น CAT-XXXX-XXXX"/></label><button className="primary small" onClick={activatePaidSerial} disabled={busy}><KeyRound size={16}/>ยืนยัน Serial</button></div></section><section className="profile-hero"><div className="profile-avatar">{data.profile.name?.[0]||'ผส'}</div><div><small>ผู้จัดทำสำนวน</small><h3>{[data.profile.rank,data.profile.name,data.profile.lastname].filter(Boolean).join(' ')||'กรอกข้อมูลผู้ใช้งาน'}</h3><p>{data.profile.station||'ยังไม่ได้ระบุสถานีตำรวจ'}</p></div></section><section className="editor-card profile-card"><div className="form-grid"><Field label="ยศ" value={data.profile.rank} placeholder="ร.ต.อ." onChange={v=>set('profile',{...data.profile,rank:v})}/><Field label="ชื่อ" value={data.profile.name} placeholder="ดลธรรม" onChange={v=>set('profile',{...data.profile,name:v})}/><Field label="นามสกุล" value={data.profile.lastname} placeholder="ศรีจันทร์ทอง" onChange={v=>set('profile',{...data.profile,lastname:v})}/><Field label="ตำแหน่ง" value={data.profile.position} placeholder="พนักงานสอบสวน" onChange={v=>set('profile',{...data.profile,position:v})}/><Field label="สถานีตำรวจ" value={data.profile.station} placeholder="สน.พหลโยธิน" onChange={v=>set('profile',{...data.profile,station:v})} wide/><Field label="โทรศัพท์" value={data.profile.phone} onChange={v=>set('profile',{...data.profile,phone:v})}/><Field label="เลขประจำตัว/ลำดับ" value={data.profile.ordinal_number} onChange={v=>set('profile',{...data.profile,ordinal_number:v})}/><Field label="ยศผู้กำกับ" value={data.profile.superintendent_rank} onChange={v=>set('profile',{...data.profile,superintendent_rank:v})}/><Field label="ชื่อผู้กำกับ" value={data.profile.superintendent_name} onChange={v=>set('profile',{...data.profile,superintendent_name:v})}/></div><div className="profile-save"><button className="primary" onClick={saveProfileOnly}><Save size={17}/>บันทึกโปรไฟล์ของฉัน</button><button className="secondary" onClick={save}><Save size={17}/>บันทึกโปรไฟล์และคดี</button></div></section></>}
 {active==='memo'&&<><SectionTitle eyebrow="MEMO" title="บันทึกพนักงานสอบสวน" desc="ระบบตรวจข้อมูลคดี บุคคล ของกลาง ฝากขัง และวันที่สรุปสำนวน เพื่อจัดรายการปฏิบัติเบื้องต้นให้ พร้อมใช้ชื่อผู้ลงบันทึกจากโปรไฟล์อัตโนมัติ"/><div className="memo-toolbar"><button className="primary small" onClick={()=>set('memo_rows',detectMemoRows(data))}><NotebookPen size={16}/>ตรวจและสร้าง Memo อัตโนมัติ</button><button className="ghost" onClick={()=>set('memo_rows',[...data.memo_rows,{...blankMemo(),sign:memoSignature}])}><Plus size={16}/>เพิ่มรายการเอง</button><div className="memo-sign-chip"><UserRound size={16}/><span>ผู้ลงบันทึก: <b>{memoSignature||'กรอกข้อมูลใน Profile ก่อน'}</b></span></div></div><div className="memo-preview"><div className="memo-preview-head"><div><small>MEMO PREVIEW</small><h3>ตัวอย่างบันทึกพนักงานสอบสวน</h3></div><span>{data.memo_rows.length} รายการ</span></div>{data.memo_rows.length===0?<div className="blank-state compact"><NotebookPen size={34}/><h3>ยังไม่มีรายการบันทึก</h3><p>กด “ตรวจและสร้าง Memo อัตโนมัติ” เพื่อดึงข้อมูลจากทุกแท็บมาเรียงเป็นรายการ</p></div>:<div className="memo-table-wrap"><table className="memo-table"><thead><tr><th>วันที่</th><th>รายการปฏิบัติ</th><th>ผู้ลงบันทึก/ลายมือชื่อ</th><th/></tr></thead><tbody>{data.memo_rows.map((row,i)=><tr key={i}><td><input type="date" value={row.date} onChange={e=>set('memo_rows',data.memo_rows.map((q,n)=>n===i?{...q,date:e.target.value}:q))}/></td><td><textarea rows={3} value={row.action} onChange={e=>set('memo_rows',data.memo_rows.map((q,n)=>n===i?{...q,action:e.target.value}:q))}/></td><td><div className="memo-sign-preview"><span>{memoSignature||'—'}</span><small>ใช้จาก Profile อัตโนมัติ</small></div></td><td><button className="icon-danger" onClick={()=>set('memo_rows',data.memo_rows.filter((_,n)=>n!==i))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>}</div></>}

 {active==='generate'&&<><SectionTitle eyebrow="GENERATE" title="กดเอกสารเพื่อสร้างได้ทันที" desc="เริ่มต้นจะไม่เลือกเอกสารไว้ให้ กดการ์ดหนึ่งครั้งเพื่อสร้าง DOCX ฉบับนั้นทันที หรือเปิดโหมดเลือกหลายรายการเพื่อรวมเป็น ZIP"/><div className="generate-layout"><section className="document-picker"><div className="picker-head"><div><small>{multiSelect?'โหมดเลือกหลายรายการ':'โหมดสร้างทีละฉบับ'}</small><h3>{multiSelect?`${selected.length} รายการที่เลือก`:'คลิกการ์ดเพื่อสร้างทันที'}</h3></div><button className={multiSelect?'primary small':'ghost'} onClick={()=>{setMultiSelect(v=>!v);setSelected([])}}>{multiSelect?'ยกเลิกโหมดเลือกหลายรายการ':'เลือกหลายรายการ'}</button></div><div className="doc-list grouped-doc-list">{groupedDocs.map(([category,items])=><section className="doc-category" key={category}><div className="doc-category-head"><span>{category}</span><small>{items.length} ฉบับ</small></div>{items.map(d=><button type="button" className={multiSelect&&selected.includes(d.id)?'doc-item selected':'doc-item'} key={d.id} onClick={()=>clickDocument(d.id)} disabled={busy}><span className="doc-icon"><FileText size={19}/></span><span><b>{d.name.split('/').pop()}</b><small>{multiSelect?'กดเพื่อเลือก/ยกเลิก':'กดเพื่อสร้าง Microsoft Word (.docx)'}</small></span>{multiSelect&&<CheckCircle2 className="doc-check" size={19}/>}</button>)}</section>)}</div></section><aside className="generate-summary"><div className="summary-ring"><strong>{progress}%</strong><span>ข้อมูลพร้อม</span></div><h3>ตรวจสอบก่อนสร้าง</h3><ul><li className={data.caseid?'ok':''}>เลขคดี</li><li className={data.charge?'ok':''}>ข้อหาและพฤติการณ์</li><li className={data.suspects.some(x=>x.name)?'ok':''}>ข้อมูลผู้ต้องหา</li><li className={data.properties.some(x=>x.item_name)?'ok':''}>รายการของกลาง</li><li className={data.profile.name&&data.profile.station?'ok':''}>โปรไฟล์พนักงานสอบสวน</li></ul>{progress<100&&<div className="warning"><AlertCircle size={18}/>ยังสร้างได้ แต่ควรกรอกข้อมูลที่ขาดเพื่อให้เอกสารสมบูรณ์</div>}{multiSelect&&<button className="generate-button" disabled={busy||selected.length===0} onClick={makeDocs}><Download size={20}/>{busy?'กำลังสร้าง...':`สร้าง ${selected.length} เอกสารเป็น ZIP`}</button>}</aside></div></>}
 </div></main></div>
}
